[build]
  command = "npm run docs:build"
  publish = ".vitepress/dist"
  node_version = "18.12.0"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.md"
  status = 200

